config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :accounts
  resources :users
  
  root to: "home#intro"
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup',  to: 'accounts#new'
  post '/signup',  to: 'accounts#create'
  
  get 'interact_chart', to: 'charts#interact_chart'
  get 'prediction_chart', to: 'charts#prediction_chart'

  get 'advocacy/index'

  get 'advocacy/import'

  get 'scientific/index'

  get 'scientific/import'

  get 'econ_recession/index'

  get 'econ_recession/import'

  get 'extweather/index'

  get 'extweather/import'
  
  
  

  resources :ccsi_elite do
    collection {post :import}
  end
  root to: "ccsi_elite#index"

  resources :extweather do
    collection {post :import}
  end
  root to: "extweather#index"
  
  resources :econ_recession do
    collection {post :import}
  end
  root to: "econ_recession#index"
  
  resources :scientific do
    collection {post :import}
  end
  root to: "scientific#index"
  
  resources :advocacy do
    collection {post :import}
  end
  root to: "advocacy#index"
  
  get 'ccsi_elite/index'

  get 'ccsi_elite/import'

  get 'csv_parse/rake'

  get 'home/lib'

  get 'home/CCSI'

  get 'home/interact', to: 'users#new'

  get 'home/intro'
  
  get '/ranks', to: 'home#ranking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :recession 
    belongs_to :account
 
   validates :prediction, presence: true, numericality: { only_integer: true, greater_than: 5.0, less_than: 50.0} 
   validates :recession_id, presence: true, numericality: {only_integer: true, greater_than: 0, less_than: 65}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    
    @options = {}
    @recessions = Recession.all
    if @recessions 
      @recessions.each do |r|
        @options[r.Date] = r.id
      end
    end
    
    @user = User.new
    @users = User.all
  
    @name = {}
    if logged_in?
      @c_account = current_account
      @name[@c_account.name] = @c_account.id
    end
    
    
  end

  # GET /users/1/edit
  def edit
        @users = User.all

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @recessions = Recession.all

    @users = User.all
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        flash[:success] = "Your prediction has been recorded below!"
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:recession_id, :prediction, :account_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  
    
<p>The Recessions table provides a summary of all the timeseries variables that help predict the CCSI. Users can refer to this data and make predictions for the CCSI for the respective “date” ids. Once the predictions are generated, they are autosaved to the User model and dynamically updated onto the Bar chart. 
</p>
<p>Valid guesses for the CCSI predictions must range between 5 – 50% while valid date ids will fall in the range: 1-64 where “1” = Q1 2000 and “64” = Q4 2015</p>
  
  <% if logged_in? %>
    <div class="field">
    <%= form.label :recession_id %>
     <%#= form.text_field :recession_id, id: :recession_id %>
    
   <%= form.select :recession_id, @options %> 

</div>

  <div class="field">
    <%= form.label :prediction %>
    <%= form.text_field :prediction, id: :user_prediction %>
  </div>
  
   <div class="field">
    <%= form.label :account_id %>
        <%#= form.text_field :account_id, id: :account_id %>

        <%= form.select :account_id, @name %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% else %>
       <div id="signuplink"> <%= link_to "To create a prediction login or signup here", login_path %>
       </div>
  <% end %>
    
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Recession</th>
      <th>Prediction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.recession_id %></td>
        <td><%= user.prediction %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="middle">
  <h1>Interactive Data</h1>

</div>


<div class="left users">
    <h1>Create CCSI Prediction</h1>
    <%= render 'form', user: @user %>
  
  
  <div class="secondtable">
    
 
    <h1>User CCSI Predictions & Recession Dates</h1>
<p>To establish this predictive charting exercise, we’ve linked the “recessions” model with the “users” model using the “recession_id”. The charting tool updates dynamically when the user makes a prediction and stores it in the users model.
</p>
<table class="table table-bordered table-striped table">
  <thead>
    <tr class="danger">
      <th>ID</th>
      <th>Recession Date</th>
      <th>CCSI Prediction</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.recession_id %></td>
        <td>
            <%= @recessions.find(user.recession_id).Date %>
        </td>
        <td><%= user.prediction %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 </div>
  <div id="signuplink"> <%= link_to "Click to View Historical User Predictions", ranks_path %>
  </div>
</div>
<div class="left helper">
  
        <h1>Recession Data</h1>

<table id="recessions" class ="table table-bordered table-condensed table-hover">
    <thead class="thread-dark">
        <tr class = "warning">
            <th>ID</th>
            <th>Date</th>
            <th>Unemployment Rate</th> 
            <th>GDP Growth Rate</th> 
            <th>Recession Dates</th> 
            <th>Nonfarm Payroll</th> 
        </tr>
    </thead>
    <tbody>
  <%@recessions.each do|r| %>
      <tr>
        <td><%=r.id%></td>
        <td><%=r.Date%></td>
        <td><%= r.Unemployment %></td>
        <td><%= r.GDPGrowth %></td>
        <td><%= r.Recession_Dates %></td>
        <td><%= r.Nonfarm_Payrolls %></td>
      </tr>
  </tbody>
  
  <%end%>
    
</table>
</div>

<div class="clear">
    
    <h1 id="charttitle"> CCSI Predictions </h1>
    
    <%= column_chart User.group(:id).maximum(:prediction), min: -40, max: 50, legend: true, label: "Predicted CCSI", xtitle: "User Number", ytitle: "Predicted CCSI", colors: ["#FF99FF", "#9900FF"] %>
    

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recession:</strong>
  <%= @user.recession_id %>
</p>
<p>
  <strong>Account:</strong>
  <%= @user.account_id %>
</p>

<p>
  <strong>Prediction:</strong>
  <%= @user.prediction %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>