config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :accounts
  resources :users
  
  root to: "home#intro"
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup',  to: 'accounts#new'
  post '/signup',  to: 'accounts#create'
  
  get 'interact_chart', to: 'charts#interact_chart'
  get 'prediction_chart', to: 'charts#prediction_chart'

  get 'advocacy/index'

  get 'advocacy/import'

  get 'scientific/index'

  get 'scientific/import'

  get 'econ_recession/index'

  get 'econ_recession/import'

  get 'extweather/index'

  get 'extweather/import'
  
  
  

  resources :ccsi_elite do
    collection {post :import}
  end
  root to: "ccsi_elite#index"

  resources :extweather do
    collection {post :import}
  end
  root to: "extweather#index"
  
  resources :econ_recession do
    collection {post :import}
  end
  root to: "econ_recession#index"
  
  resources :scientific do
    collection {post :import}
  end
  root to: "scientific#index"
  
  resources :advocacy do
    collection {post :import}
  end
  root to: "advocacy#index"
  
  get 'ccsi_elite/index'

  get 'ccsi_elite/import'

  get 'csv_parse/rake'

  get 'home/lib'

  get 'home/CCSI'

  get 'home/interact', to: 'users#new'

  get 'home/intro'
  
  get '/ranks', to: 'home#ranking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def lib
   @recessions = Recession.all
   @media = Medium.all
   @elite_cues = EliteCue.all
   @weathers = Weather.all
   @sciences = Science.all
  end

  def CCSI
  end

  def interact
      @users = User.all
  end
  
  def ranking
       @users = User.all
       @rank = {} 
       @recessions = Recession.all
       @accounts = Account.all
       @users.each do|u|
            @rank[u.id] = (@recessions.find(u.recession_id).CCSI - u.prediction).abs
       end 
       #@rank = @rank.sort_by { |k, v| v }
    #   min = @rank.first
    #   @sorted = {}
    #   min_k = @rank.first.key
    #   @rank.each do |k,v|
    #       if v < min.v
    #           min_k = k
    #           min.v = v
    #       end
    #   end
    #   @sorted[min_k] = min.v
               
  end
 
  def intro
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/CCSI.html.erb
<h1>Climate Change Sceptic Index (CCSI)</h1>
<div>
    <h3> What is the CCSI? </h3>
        <p> The CCSI is an aggregate-level measure of climate scepticism in the US and acts as a proxy to run regression analysis to determine what
        factors help predict the level of scepticism in the US.
        </p>
</div>



<%= line_chart EliteCue.group(:Date).maximum(:CCSI), label: "CCSI in period", xtitle: "Period Number", ytitle: "CCSI", min: 15, max: 35, colors: ["#6CF904"] %>

app/views/home/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recession_id %>
    <%= form.number_field :recession_id, id: :user_recession_id %>
  </div>


  <div class="field">
    <%= form.label :prediction %>
    <%= form.text_field :prediction, id: :user_prediction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home/interact.html.erb
<h1>Interactive Data</h1>
<p>Blueprint: </p>
<p><ul>
    <li> User Form with options to variables and populate graphs (dynamic charting)</li>
    <li> Datasets and graphs of key findings from research </li>
    
</ul> 

</p>
<%= line_chart interact_chart_path %>

app/views/home/intro.html.erb
<div class="jumbotron jumbotron-fluid">
    <h2>Recessions or Polarization: What Influences Climate Scepticism in the US?</h2>
    <%= link_to "Download Research PDF", 'https://drive.google.com/file/d/1aFPhy9gl3eoVuRgEdLo1uFDXbfO6T-pE/view?usp=sharing',target: "_blank", class: "btn btn-lg btn-primary"%>
    <div class="map">    <%= image_tag("effects.jpg", alt: "map") %>
</div>
    <h3><b> Climate Scepticism Web Application Walkthrough: </b></h3>
    <p>
        <ol> 
        <li> Home: The home page provides usage guidelines and will host PDF copies of the Economics senior thesis and supplementary materials.</li> 
        <li> Library: Provides information and stores the timeseries data used in the thesis.</li>
        <li> Interactive Data: Allows the user to engage in predictive modelling and charting of the Climate Change Sceptic Index (CCSI) based on the Recessionary variable data table.</li>
        <li> CCSI: Provides a written and visual depiction of the CCSI and information about its computation.</li>
        </ol>
<h5><I> About the Logo: “ManBearPig” </I></h5>
<small> ManBearPig is the title of the sixth episode in the tenth season of the hit 
    American animated TV series “South Park”. In the episode,
    Al Gore visits South Park to warn everyone about a creature called ManBearPig, 
    an allegory for global warming. The creature is actually a homage from the 
    eco-horror cult film Prophecy directed by John Frankenheimer wherein the film's 
    monster is a result of, basically, the environment.
    Our icon provides a link to a snippet of this episode. </small>
</p>
</div>

app/views/home/lib.html.erb
<h1> All Timeseries Variables used for Vector Autoregression </h1>

<p><small>This page is a library that hosts all the timeseries variables that are used in the regression analysis to predict the CCSI. For the purposes of this project, we only use the “recessionary variables” data to allow users to generate predictions for the model. This library will be used to allow users
additional functionality such as generating regressions and testing data analysis results discussed in the thesis.
</small>
</p>

<h2> Economic Recessionary Factors</h2>
<table id="recessions" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th> Id </th>
            <th> Date </th>
            <th> CCSI </th>
            <th> Unemployment Rate</th>
            <th> GDP Growth (%change)</th>
            <th> Price of Oil </th>
            <th> Industrial Production Index </th>
            <th> Recession Dates </th>
            <th> Total Nonfarm Payrolls (%change) </th>
        </tr>
    </thead>
    <tbody>
        <% @recessions.each do |n| %>
        <tr>
            <td> <%= n.id %></td>
            <td> <%= n.Date %></td>
            <td> <%= n.CCSI %></td>
            <td> <%= n.Unemployment %></td>
            <td> <%= n.GDPGrowth %></td>
            <td> <%= n.Oil_Price %></td>
            <td> <%= n.IPI %></td>
            <td> <%= n.Recession_Dates %></td>
            <td> <%= n.Nonfarm_Payrolls %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<h2> Media Advocacy and Coverage</h2>
<table id= "media" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th> Id </th>
            <th> Date </th>
            <th> CCSI </th>
            <th> Media Index (Coverage) </th>
            <th> Count of Environmental Magazines</th>
            <th> Count of Conservative Magazines</th>
        </tr>
    </thead>
    <tbody>
        <% @media.each do |n| %>
        <tr>
            <td> <%= n.id %></td>
            <td> <%= n.Date %></td>
            <td> <%= n.CCSI %></td>
            <td> <%= n.Media_Index %></td>
            <td> <%= n.Environmental_Magazines %></td>
            <td> <%= n.Conservative_Magazines %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<h3> Political Elite Cues</h3>
<table id="politics" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th> Id </th>
            <th> Date </th>
            <th> CCSI </th>
            <th> Democrat Statements For CC</th>
            <th> Republican Statements Against CC</th>
            <th> House Hearings on CC </th>
            <th> Senate Hearings on CC </th>
            <th> LCV Dem Pro-CC Score </th>
            <th> LCV Republican Anti-CC Score</th>
        </tr>
    </thead>
    <tbody>
        <% @elite_cues.each do |n| %>
        <tr>
            <td> <%= n.id %></td>
            <td> <%= n.Date %></td>
            <td> <%= n.CCSI %></td>
            <td> <%= n.Democrat_Statements %></td>
            <td> <%= n.Republican_Statements %></td>
            <td> <%= n.House_Hearings %></td>
            <td> <%= n.Senate_Hearings %></td>
            <td> <%= n.LCV_Dem %></td>
            <td> <%= n.LCV_Rep %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<h2> Extreme Weather Conditions</h2>
<table id="extreme" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th> Id </th>
            <th> Date </th>
            <th> CCSI </th>
            <th> CEI</th>
            <th> Warm Areas</th>
            <th> Cold Areas </th>
            <th> DSCI </th>
        </tr>
    </thead>
    <tbody>
        <% @weathers.each do |n| %>
        <tr>
            <td> <%= n.id %></td>
            <td> <%= n.Date %></td>
            <td> <%= n.CCSI %></td>
            <td> <%= n.CEI %></td>
            <td> <%= n.Warm_Areas %></td>
            <td> <%= n.Cold_Areas %></td>
            <td> <%= n.DSCI %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<h2> Scientific Information on Climate Change</h2>
<table id="science" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th> Id </th>
            <th> Date </th>
            <th> CCSI </th>
            <th> Popular Scientific Magazine Articles </th>
            <th> Release of Major Scientific Report</th>
        </tr>
    </thead>
    <tbody>
        <% @sciences.each do |n| %>
        <tr>
            <td> <%= n.id %></td>
            <td> <%= n.Date %></td>
            <td> <%= n.CCSI %></td>
            <td> <%= n.Scientific_Magazines %></td>
            <td> <%= n.Scientific_Reports %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/home/ranking.html.erb
<h1>Record of All Predictions</h1>

<table class = "table table-bordered table-striped">
    <th>Recession ID</th>
    <th>Account</th>
    <th>Prediction</th>
    <th>Actual CCSI</th>
    <th>Difference</th>
    <!--<%#= @rank %>-->
        <%@rank.each_key do |r| %>
            <tr>
                <td><%=@recessions.find(@users.find(r).recession_id).Date %></td>
                <td><%=@accounts.find(@users.find(r).account_id).name %></td>
                <td><%=(@users.find(r)).prediction %></td>
                <td><%=@recessions.find(@users.find(r).recession_id).CCSI %></td>
                <td><%=@rank[r] %></td>
            </tr>
        <%end%>
</table>