config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :accounts
  resources :users
  
  root to: "home#intro"
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup',  to: 'accounts#new'
  post '/signup',  to: 'accounts#create'
  
  get 'interact_chart', to: 'charts#interact_chart'
  get 'prediction_chart', to: 'charts#prediction_chart'

  get 'advocacy/index'

  get 'advocacy/import'

  get 'scientific/index'

  get 'scientific/import'

  get 'econ_recession/index'

  get 'econ_recession/import'

  get 'extweather/index'

  get 'extweather/import'
  
  
  

  resources :ccsi_elite do
    collection {post :import}
  end
  root to: "ccsi_elite#index"

  resources :extweather do
    collection {post :import}
  end
  root to: "extweather#index"
  
  resources :econ_recession do
    collection {post :import}
  end
  root to: "econ_recession#index"
  
  resources :scientific do
    collection {post :import}
  end
  root to: "scientific#index"
  
  resources :advocacy do
    collection {post :import}
  end
  root to: "advocacy#index"
  
  get 'ccsi_elite/index'

  get 'ccsi_elite/import'

  get 'csv_parse/rake'

  get 'home/lib'

  get 'home/CCSI'

  get 'home/interact', to: 'users#new'

  get 'home/intro'
  
  get '/ranks', to: 'home#ranking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/advocacy_controller.rb
class AdvocacyController < ApplicationController
  def index
    @media = Medium.all
  end

  def import
    Medium.import(params[:file])
    redirect_to root_url, notice: "Data imported."
  end
end

app/helpers/advocacy_helper.rb
module AdvocacyHelper
end

app/views/advocacy/import.html.erb
<h1>Advocacy#import</h1>
<p>Find me in app/views/advocacy/import.html.erb</p>

app/views/advocacy/index.html.erb
<%= flash[:notice] %>
<table>
    <thead>
        <tr>
            <th> Id </th>
            <th> Date </th>
            <th> CCSI </th>
            <th> Media Index (Coverage) </th>
            <th> Count of Environmental Magazines</th>
            <th> Count of Conservative Magazines</th>
        </tr>
    </thead>
    <tbody>
        <% @media.each do |n| %>
        <tr>
            <td> <%= n.id %></td>
            <td> <%= n.Date %></td>
            <td> <%= n.CCSI %></td>
            <td> <%= n.Media_Index %></td>
            <td> <%= n.Environmental_Magazines %></td>
            <td> <%= n.Conservative_Magazines %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<div>
    <h3> Import a CSV File</h3>
    <%= form_tag import_advocacy_index_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
    <% end %>
</div>