config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :accounts
  resources :users
  
  root to: "home#intro"
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup',  to: 'accounts#new'
  post '/signup',  to: 'accounts#create'
  
  get 'interact_chart', to: 'charts#interact_chart'
  get 'prediction_chart', to: 'charts#prediction_chart'

  get 'advocacy/index'

  get 'advocacy/import'

  get 'scientific/index'

  get 'scientific/import'

  get 'econ_recession/index'

  get 'econ_recession/import'

  get 'extweather/index'

  get 'extweather/import'
  
  
  

  resources :ccsi_elite do
    collection {post :import}
  end
  root to: "ccsi_elite#index"

  resources :extweather do
    collection {post :import}
  end
  root to: "extweather#index"
  
  resources :econ_recession do
    collection {post :import}
  end
  root to: "econ_recession#index"
  
  resources :scientific do
    collection {post :import}
  end
  root to: "scientific#index"
  
  resources :advocacy do
    collection {post :import}
  end
  root to: "advocacy#index"
  
  get 'ccsi_elite/index'

  get 'ccsi_elite/import'

  get 'csv_parse/rake'

  get 'home/lib'

  get 'home/CCSI'

  get 'home/interact', to: 'users#new'

  get 'home/intro'
  
  get '/ranks', to: 'home#ranking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
    before_save {email.downcase}
    has_many :users
    validates :name, presence: true, length: {maximum: 50}
    VALIDE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email,  presence:   true,   length: {maximum:  150}, 
    format:  {with:   VALIDE_EMAIL_REGEX},  uniqueness:  {case_sensitive:  false}

    has_secure_password
    validates   :password, length: {minimum:  8} 



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/elite_cue.rb
class EliteCue < ApplicationRecord
    require 'csv'
    
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            
            elite_hash = row.to_hash
            cue = EliteCue.where(id: elite_hash["id"])
            
            if cue.count == 1
                cue.first.update_attributes(elite_hash)
            else
                EliteCue.create!(elite_hash)
            end
        end
    end
end

app/models/medium.rb
class Medium < ApplicationRecord
    require 'csv'
    
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            
            media_hash = row.to_hash
            meds = Medium.where(id: media_hash["id"])
            
            if meds.count == 1
                meds.first.update_attributes(media_hash)
            else
                Medium.create!(media_hash)
            end
        end
    end

end

app/models/recession.rb
class Recession < ApplicationRecord
    has_many :users
require 'csv'
    
 #   def self.import(file)
 #       CSV.foreach(file.path, headers: true) do |row|
            
 #            recession_hash = row.to_hash
#            recessions = Recession.where(id: recession_hash["id"])
            
#            if recessions.count == 1
#                recessions.first.update_attributes(recession_hash)
#            else
#                Recession.create!(recession_hash)
#            end
#        end
#    end

end

app/models/science.rb
class Science < ApplicationRecord
require 'csv'
    
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            
            science_hash = row.to_hash
            science1 = Science.where(id: science_hash["id"])
            
            if science1.count == 1
                science1.first.update_attributes(science_hash)
            else
                Science.create!(science_hash)
            end
        end
    end


end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :recession 
    belongs_to :account
 
   validates :prediction, presence: true, numericality: { only_integer: true, greater_than: 5.0, less_than: 50.0} 
   validates :recession_id, presence: true, numericality: {only_integer: true, greater_than: 0, less_than: 65}

end

app/models/weather.rb
class Weather < ApplicationRecord
    require 'csv'
    
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            
            weather_hash = row.to_hash
            weathers = Weather.where(id: weather_hash["id"])
            
            if weathers.count == 1
                weathers.first.update_attributes(weather_hash)
            else
                Weather.create!(weather_hash)
            end
        end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def lib
   @recessions = Recession.all
   @media = Medium.all
   @elite_cues = EliteCue.all
   @weathers = Weather.all
   @sciences = Science.all
  end

  def CCSI
  end

  def interact
      @users = User.all
  end
  
  def ranking
       @users = User.all
       @rank = {} 
       @recessions = Recession.all
       @accounts = Account.all
       @users.each do|u|
            @rank[u.id] = (@recessions.find(u.recession_id).CCSI - u.prediction).abs
       end 
       #@rank = @rank.sort_by { |k, v| v }
    #   min = @rank.first
    #   @sorted = {}
    #   min_k = @rank.first.key
    #   @rank.each do |k,v|
    #       if v < min.v
    #           min_k = k
    #           min.v = v
    #       end
    #   end
    #   @sorted[min_k] = min.v
               
  end
 
  def intro
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/advocacy_helper.rb
module AdvocacyHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ccsi_elite_helper.rb
module CcsiEliteHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/csv_parse_helper.rb
module CsvParseHelper
end

app/helpers/extweather_helper.rb
module ExtweatherHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scientific_helper.rb
module ScientificHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(account)
        session[:account_id] = account.id
    end
    
    def current_account
        if @current_account.nil?
            @current_account = Account.find_by(id: session[:account_id])
        else
            @current_account
        end
    end
    def logged_in?
        !current_account.nil?
    end
    
    def log_out
        session.delete(:account_id)
        @current_account = nil
    end
    
    def current_account?(account)
        account == current_account
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class=”footer”>
<small>
   Designed by: Gino, Erica, and Abhi.
</small>
<nav>
<ul>
   <li><%= link_to "Interactive Data", controller: "users", action: "new"%></li>
   <li><%= link_to "CCSI", controller: "home", action: "CCSI"%> </li>
   <li><%= link_to "Library", controller: "home", action: "lib"%> </li>
   <li><%= link_to "Home", controller: "home", action: "intro" %></li>
   <li><a href=”http://www.depauw.edu”>DePauw</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recession_id %>
    <%= form.number_field :recession_id, id: :user_recession_id %>
  </div>

  <div class="field">
    <%= form.label :prediction %>
    <%= form.text_field :prediction, id: :user_prediction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
     
      <%= link_to image_tag( "ManBearPig.png", alt: "ManBearPig", id: "logo" ), "https://www.youtube.com/watch?v=0AW4nSq0hAc", target: "_blank" %>

    
        <nav>
          <ul class= "nav navbar-nav navbar-right">
            <li><%= link_to "Home", controller: "home", action: "intro" %></li>
            <li><%= link_to "Library", controller: "home", action: "lib"%> </li>
            <li><%= link_to "Interactive Data", controller: "users", action: "new"%></li>
            <li><%= link_to "CCSI DATA", controller: "home", action: "CCSI"%> </li>
            
            <% if logged_in? %>
                <li><%= link_to "Accounts", accounts_path %></li>
                 <li class= "dropdown">
                  <a href= "#" class= "dropdown-toggle" data-toggle= "dropdown">
                  Account <b class= "caret"></b>
                  </a>
                 <ul class= "dropdown-menu">
                  <li><%= link_to "Profile", current_account %></li>
	                <li><%= link_to "Settings", edit_account_path(current_account) %></li>
	                <li class= "divider"></li>
                  <li><%= link_to "Log out", logout_path, method: :delete %></li>
                 </ul>
                </li>
               <% else %>
                  <li><%= link_to "Log in", login_path %></li>
              <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<script src= "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Climate Scepticism in the US</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type%>"><%= message %></div>
      <% end %>
  </body>
  
        <%= render 'layouts/footer' %>
  </div>
</html>